import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { useTranslation } from "react-i18next";
import { ThemeContext, ThemeContextType } from "../context/theme";

const Home: NextPage = () => {
  const { isFontLarge, setIsFontLarge, isMonochrome, setIsMonochrome } =
    useContext(ThemeContext) as ThemeContextType;
  const { t, i18n } = useTranslation();

  const switchLanguage = () =>
    i18n.language === "en"
      ? i18n.changeLanguage("pl")
      : i18n.changeLanguage("en");

  return (
    <div
      className={isMonochrome ? "dark" : ""}
      style={isFontLarge ? { fontSize: "20px" } : {}}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white dark:bg-gray-400 flex flex-col gap-4 h-screen">
        <button onClick={() => setIsMonochrome(!isMonochrome)}>
          Switch to dark mode
        </button>
        <button onClick={() => setIsFontLarge(!isFontLarge)}>
          Switch font size
        </button>
        <button onClick={() => switchLanguage()}>Switch to polish</button>

        <p className="text-center">{t("testText")}</p>
      </main>
    </div>
  );
};

export default Home;
