import type { NextPage } from "next";
import Head from "next/head";
import { useTranslation } from "react-i18next";
import Ballads from "../components/Ballads";

const Home: NextPage = () => {
  const { t } = useTranslation();

  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Ballads />
    </div>
  );
};

export default Home;
